### ISSUE TITLE
Add support for 2D histograms

### ISSUE THREAD

**Issue by joeycarter** [joeycarter/atlas-plots#2]
Currently, the `Axes` object only supports 1D histograms and graphs (`TH1`s, `TGraph`s, etc.). `Axes` should also support displaying multidimensional data structures, such as 2D histograms (`TH2`s), and the relevant `Axes` methods should be modified accordingly.

**Comment by xzf89718** [comment]
Hi, Joey. Very useful update, thanks your nive work. 
The plot2d is not available on the Pypi way installed atlasplots. i.e. pip install atlasplots. But it works well installed by source via git. Maybe you could upload the latest update to Pypi.

**Comment by joeycarter** [comment]
Hi Zifeng,

A new release is only built and deployed to PyPI when a new tag is created. I've created tag v0.1.7 (commit cdff6ed); this version is now deployed on PyPI and should have support for `ax.plot2d()`.

Cheers,
Joey
